### ISSUE TITLE
DualSense motion

### ISSUE THREAD

**Issue by Anuskuss** [Anuskuss/cemu#1]
Hey @AMDBartek I'm banned from the Cemu GitHub but I saw your issue and wanted to help.
Motion (and Rumble) is already supported through SDL but you have to manually edit the XML files (`controllerX.xml`).
If you use my [cemu package from the AUR](https://aur.archlinux.org/packages/cemu) it's at
```
~/.config/cemu/controllerProfiles/controller0.xml
```
Change these values:
```xml
<motion>true</motion>
<rumble>1</rumble>
```

As for the lower FPS, v2.0 is overall slower than v1 (even on Windows that is). It's been speculated that Exzap wrote his earlier code based on the [leaked Wii U SDK](https://web.archive.org/web/20140701062743/http://wiiuhax.com/wii-u-sdk-leaked/) and has generally benefitted from open-source software while being closed-sourced (which violates the respective licenses). After deciding to go open source, a bunch of code paths had to be rewritten which resulted in slower performance. As I said, you can see the same performance degradation on Windows but I'm confident that all "lost" FPS will return in the future.
As for Linux performance, we're not really sure. If you can afford it (= if your hardware is powerful enough to reach 100% regardless), I'd go with the native build. If you can't, you can't really go wrong with Wine + v1.27.1.

P.S. Don't use the open source Nvidia driver yet. That's still missing some features and performance is generally worse. If it's ready, it'll go into the kernel anyways.

**Comment by AMDBartek** [comment]
Its also not a hardware issue since it is rather powerful. I'll just wait and see if Cemu 2.0 gets better. For now I'll be using the older builds on Wine.

**Comment by Anuskuss** [comment]
For me my hardware is just strong enough to reach 100% in every game I play so I'll be using the native version. The only big thing left for me is Online Play but atleast VSync works (which didn't on Wine last time I checked).

Also consider updating (and closing) your issue on Cemu's GitHub because others might also be looking for a solution to the same problem.
